version: '3.8'

services:
  social-recipe-saver:
    image: ghcr.io/minemap-nl/socialrecipesaver:latest
    container_name: Social-Recipe-Saver
    restart: always
    stop_grace_period: 5s
    ports:
      - "9416:3000"
    volumes:
      - ./db:/app/data
      - ./thumbnails:/app/public/thumbnails
      - ./videos:/app/public/videos
      - ./backups:/app/backups
    environment:
      - DATABASE_URL=file:/app/data/dev.db
      - SMTP_HOST=your-smtp-host
      - SMTP_PORT=587
      - SMTP_USER=your-email
      - SMTP_PASS=your-password
      - PROCESS_METHOD=ai # Set to 'manual' to disable AI features
      - GEMINI_API_KEY=your-gemini-api-key
      - APP_NAME=Social Recipe Saver
      - APP_URL=https://recepten.yourdomain.com
      - SITE_PASSWORD=your-secret-password
      - JWT_SECRET=your-random-jwt-secret
      - AUTO_BACKUP=true
