#!/usr/bin/env node
/**
 * Local helper: open a clean browser window → you log into Instagram →
 * export Netscape cookies → optionally upload to ClipCookBook.
 *
 * Usage:
 *   bun install
 *   bunx playwright install chromium
 *   bun run refresh -- --url https://recepten.example.com --password "SITE_PASSWORD"
 *
 * Env alternatives: APP_URL, SITE_PASSWORD, COOKIES_OUT
 */
import { chromium } from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function parseArgs(argv) {
    const out = { url: process.env.APP_URL || '', password: process.env.SITE_PASSWORD || '', out: process.env.COOKIES_OUT || '', noUpload: false };
    for (let i = 0; i < argv.length; i++) {
        const a = argv[i];
        if (a === '--url') out.url = argv[++i] || '';
        else if (a === '--password') out.password = argv[++i] || '';
        else if (a === '--out') out.out = argv[++i] || '';
        else if (a === '--no-upload') out.noUpload = true;
        else if (a === '--help' || a === '-h') out.help = true;
    }
    return out;
}

function toNetscape(cookies) {
    const lines = [
        '# Netscape HTTP Cookie File',
        '# Generated by ClipCookBook tools/instagram-cookies',
        '# This file is generated by yt-dlp. Do not edit.',
        '',
    ];
    for (const c of cookies) {
        const domain = c.domain.startsWith('.') ? c.domain : c.domain;
        const includeSub = domain.startsWith('.') ? 'TRUE' : 'FALSE';
        const cookiePath = c.path || '/';
        const secure = c.secure ? 'TRUE' : 'FALSE';
        const expires = c.expires && c.expires > 0 ? Math.floor(c.expires) : 0;
        const name = c.name;
        const value = c.value;
        lines.push([domain, includeSub, cookiePath, secure, expires, name, value].join('\t'));
    }
    return lines.join('\n') + '\n';
}

async function waitForInstagramLogin(context, page, timeoutMs = 10 * 60 * 1000) {
    const start = Date.now();
    console.log('Log in to Instagram in the opened window (use a throwaway account if you can).');
    console.log('Waiting until a sessionid cookie appears…');

    while (Date.now() - start < timeoutMs) {
        const cookies = await context.cookies('https://www.instagram.com');
        if (cookies.some((c) => c.name === 'sessionid' && c.value)) {
            // Give IG a moment to set related cookies
            await new Promise((r) => setTimeout(r, 1500));
            return;
        }
        await new Promise((r) => setTimeout(r, 1000));
    }
    throw new Error('Timed out waiting for Instagram login (sessionid).');
}

async function main() {
    const args = parseArgs(process.argv.slice(2));
    if (args.help) {
        console.log(`Usage: bun run refresh -- --url https://your-app --password SITE_PASSWORD [--out cookies.txt] [--no-upload]`);
        process.exit(0);
    }

    const browser = await chromium.launch({
        headless: false,
        args: ['--disable-blink-features=AutomationControlled'],
    });

    // Fresh context ≈ private/incognito window
    const context = await browser.newContext({
        viewport: { width: 1280, height: 900 },
        locale: 'nl-NL',
        userAgent:
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
    });
    const page = await context.newPage();
    await page.goto('https://www.instagram.com/accounts/login/', { waitUntil: 'domcontentloaded' });

    try {
        await waitForInstagramLogin(context, page);
        const all = await context.cookies();
        const ig = all.filter(
            (c) =>
                c.domain.includes('instagram.com') ||
                c.domain.includes('cdninstagram.com') ||
                c.domain.includes('facebook.com')
        );
        if (!ig.some((c) => c.name === 'sessionid')) {
            throw new Error('Login finished but sessionid cookie missing.');
        }

        const netscape = toNetscape(ig);
        const outPath = path.resolve(args.out || path.join(__dirname, 'cookies.txt'));
        fs.writeFileSync(outPath, netscape, 'utf8');
        console.log(`Saved local copy: ${outPath}`);

        if (!args.noUpload) {
            if (!args.url) {
                console.warn('No --url / APP_URL set; skipping upload. Use --url https://your-app');
            } else if (!args.password) {
                console.warn('No --password / SITE_PASSWORD set; skipping upload (or use --no-upload).');
            } else {
                const endpoint = new URL('/api/admin/ytdlp-cookies', args.url).href;
                const res = await fetch(endpoint, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        Authorization: `Bearer ${args.password}`,
                    },
                    body: JSON.stringify({ cookies: netscape, password: args.password }),
                });
                const data = await res.json().catch(() => ({}));
                if (!res.ok) {
                    throw new Error(data.error || `Upload failed HTTP ${res.status}`);
                }
                console.log('Uploaded to ClipCookBook:', data.message || data.path || 'ok');
            }
        }

        console.log('Done. You can close the browser window.');
    } finally {
        await browser.close().catch(() => {});
    }
}

main().catch((e) => {
    console.error(e instanceof Error ? e.message : e);
    process.exit(1);
});
