import fs from 'fs';
import fsPromises from 'fs/promises';
import path from 'path';

/** Default on-disk location when YT_DLP_COOKIES is unset (Docker: /app/data/cookies.txt). */
export function getYtdlpCookiesPath(): string {
    const raw = process.env.YT_DLP_COOKIES?.trim();
    if (raw) {
        return path.isAbsolute(raw) ? raw : path.resolve(process.cwd(), raw);
    }
    return path.resolve(process.cwd(), 'data', 'cookies.txt');
}

/** Operator opted into cookies (env set) or a cookies file already exists. */
export function areYtdlpCookiesConfigured(): boolean {
    if (process.env.YT_DLP_COOKIES?.trim()) return true;
    try {
        return fs.existsSync(getYtdlpCookiesPath());
    } catch {
        return false;
    }
}

export function getYtdlpCookieFlags(): { cookies?: string } {
    const cookiePath = getYtdlpCookiesPath();
    try {
        if (!fs.existsSync(cookiePath) || !fs.statSync(cookiePath).isFile()) {
            if (process.env.YT_DLP_COOKIES?.trim()) {
                console.warn(`[yt-dlp] YT_DLP_COOKIES set but file missing: ${cookiePath}`);
            }
            return {};
        }
    } catch {
        return {};
    }
    return { cookies: cookiePath };
}

export function withYtdlpCookies<T extends Record<string, unknown>>(flags: T): T & { cookies?: string } {
    return { ...flags, ...getYtdlpCookieFlags() };
}

export function isYtdlpAuthError(err: unknown): boolean {
    const msg = err instanceof Error ? err.message : String(err);
    return /empty media response|login required|cookies|authentication|rate-limit|Please log in/i.test(
        msg
    );
}

export function formatYtdlpError(err: unknown): string {
    const msg = err instanceof Error ? err.message : String(err);
    if (isYtdlpAuthError(err)) {
        return (
            'Instagram blokkeert videodownload zonder login. ' +
            'Het recept kan vaak wél uit de beschrijving worden gehaald; zo niet, gebruik de foto-tab of vernieuw cookies via /cookies. ' +
            `(${msg.split('\n')[0]})`
        );
    }
    return msg;
}

export type NetscapeCookieCheck = {
    ok: boolean;
    error?: string;
    lineCount: number;
    hasSessionId: boolean;
    hasDsUserId: boolean;
};

/** Basic Netscape cookies.txt validation (yt-dlp compatible). */
export function validateNetscapeCookies(text: string): NetscapeCookieCheck {
    const normalized = text.replace(/^\uFEFF/, '').trim();
    if (!normalized) {
        return { ok: false, error: 'Leeg cookiebestand.', lineCount: 0, hasSessionId: false, hasDsUserId: false };
    }

    const lines = normalized.split(/\r?\n/).filter((l) => l.trim().length > 0);
    const dataLines = lines.filter((l) => !l.trim().startsWith('#'));
    if (dataLines.length === 0) {
        return {
            ok: false,
            error: 'Geen cookieregels gevonden (alleen commentaar).',
            lineCount: 0,
            hasSessionId: false,
            hasDsUserId: false,
        };
    }

    let hasSessionId = false;
    let hasDsUserId = false;
    for (const line of dataLines) {
        const parts = line.split('\t');
        if (parts.length < 7) {
            return {
                ok: false,
                error: `Ongeldige Netscape-regel (verwacht tab-gescheiden velden): ${line.slice(0, 60)}…`,
                lineCount: dataLines.length,
                hasSessionId,
                hasDsUserId,
            };
        }
        const name = parts[5];
        if (name === 'sessionid') hasSessionId = true;
        if (name === 'ds_user_id') hasDsUserId = true;
    }

    if (!hasSessionId) {
        return {
            ok: false,
            error: 'Geen Instagram sessionid-cookie gevonden. Log eerst in op Instagram en exporteer opnieuw.',
            lineCount: dataLines.length,
            hasSessionId,
            hasDsUserId,
        };
    }

    return { ok: true, lineCount: dataLines.length, hasSessionId, hasDsUserId };
}

export async function writeYtdlpCookiesFile(text: string): Promise<{ path: string }> {
    const check = validateNetscapeCookies(text);
    if (!check.ok) throw new Error(check.error || 'Ongeldig cookiebestand');

    const cookiePath = getYtdlpCookiesPath();
    await fsPromises.mkdir(path.dirname(cookiePath), { recursive: true });
    const body = text.replace(/^\uFEFF/, '');
    const withHeader = body.includes('Netscape')
        ? body
        : `# Netscape HTTP Cookie File\n# Generated by ClipCookBook\n${body}`;
    await fsPromises.writeFile(cookiePath, withHeader.endsWith('\n') ? withHeader : withHeader + '\n', {
        mode: 0o600,
        encoding: 'utf8',
    });
    return { path: cookiePath };
}

export async function readYtdlpCookiesStatus(): Promise<{
    configured: boolean;
    path: string;
    exists: boolean;
    mtime: string | null;
    size: number | null;
    hasSessionId: boolean | null;
}> {
    const cookiePath = getYtdlpCookiesPath();
    const configured = areYtdlpCookiesConfigured();
    try {
        const st = await fsPromises.stat(cookiePath);
        const raw = await fsPromises.readFile(cookiePath, 'utf8');
        const check = validateNetscapeCookies(raw);
        return {
            configured,
            path: cookiePath,
            exists: true,
            mtime: st.mtime.toISOString(),
            size: st.size,
            hasSessionId: check.hasSessionId,
        };
    } catch {
        return {
            configured,
            path: cookiePath,
            exists: false,
            mtime: null,
            size: null,
            hasSessionId: null,
        };
    }
}
